package com.iqlock.app.ui

import android.app.KeyguardManager
import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import android.content.IntentFilter
import android.graphics.drawable.Drawable
import android.os.Build
import android.os.Bundle
import android.os.CountDownTimer
import android.view.View
import android.view.WindowManager
import android.view.animation.AnimationUtils
import android.view.inputmethod.EditorInfo
import android.view.inputmethod.InputMethodManager
import androidx.activity.viewModels
import androidx.appcompat.app.AppCompatActivity
import androidx.lifecycle.lifecycleScope
import com.google.android.material.button.MaterialButton
import com.iqlock.app.R
import com.iqlock.app.databinding.ActivityThreeStageLockBinding
import com.iqlock.app.engine.MasterChallenge
import com.iqlock.app.viewmodel.ThreeStageViewModel
import com.iqlock.app.viewmodel.ThreeStageViewModel.SessionState
import dagger.hilt.android.AndroidEntryPoint
import kotlinx.coroutines.Job
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import java.util.concurrent.TimeUnit

/**
 * ThreeStageLockActivity.kt — Full-screen overlay that drives the three-stage
 * IQ unlock flow.
 *
 * Window flags ensure it appears on top of the locked screen, even over the
 * system keyguard, and turns the screen on if needed.
 *
 * Stages:
 *  1. Stage 1: Bank-A riddle (mathematical/deductive) — text input.
 *  2. Stage 2: Bank-B riddle (abstract/pattern) — text input.
 *  3. Stage 3: Master challenge — 6-option multiple choice generated by
 *     [RelationshipEngine] from the specific pair of Stage 1 + Stage 2 answers.
 */
@AndroidEntryPoint
class ThreeStageLockActivity : AppCompatActivity() {

    companion object {
        const val EXTRA_PACKAGE_NAME = "extra_package_name"
        const val EXTRA_APP_LABEL    = "extra_app_label"
        const val ACTION_DISMISS     = "com.iqlock.app.DISMISS_THREE_STAGE"
    }

    private lateinit var binding: ActivityThreeStageLockBinding
    private val viewModel: ThreeStageViewModel by viewModels()

    private var lockoutCountdownTimer: CountDownTimer? = null
    private var hintJob: Job? = null

    // ── Lifecycle ─────────────────────────────────────────────────────────────

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        applyWindowFlags()
        binding = ActivityThreeStageLockBinding.inflate(layoutInflater)
        setContentView(binding.root)

        val pkg   = intent.getStringExtra(EXTRA_PACKAGE_NAME) ?: run { finish(); return }
        val label = intent.getStringExtra(EXTRA_APP_LABEL) ?: pkg

        setupDismissReceiver()
        setupButtons()

        // Only start a new session on first creation (survive rotation)
        if (savedInstanceState == null) {
            viewModel.startSession(pkg, label)
        }

        observeState(label)
    }

    override fun onDestroy() {
        super.onDestroy()
        lockoutCountdownTimer?.cancel()
        hintJob?.cancel()
        try { unregisterReceiver(dismissReceiver) } catch (_: Exception) {}
    }

    // ── Window Flags ──────────────────────────────────────────────────────────

    private fun applyWindowFlags() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O_MR1) {
            setShowWhenLocked(true)
            setTurnScreenOn(true)
            val km = getSystemService(Context.KEYGUARD_SERVICE) as KeyguardManager
            km.requestDismissKeyguard(this, null)
        } else {
            @Suppress("DEPRECATION")
            window.addFlags(
                WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED or
                WindowManager.LayoutParams.FLAG_TURN_SCREEN_ON or
                WindowManager.LayoutParams.FLAG_DISMISS_KEYGUARD
            )
        }
        window.addFlags(
            WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON or
            WindowManager.LayoutParams.FLAG_ALLOW_LOCK_WHILE_SCREEN_ON
        )
    }

    // ── State Observer ────────────────────────────────────────────────────────

    private fun observeState(appLabel: String) {
        lifecycleScope.launch {
            viewModel.state.collect { state ->
                when (state) {
                    is SessionState.Idle -> showLoading()

                    is SessionState.Stage1 -> {
                        showQuestionPanel()
                        setStepIndicator(1)
                        binding.tvStageBadge.text = "CHALLENGE I — LOGICAL DEDUCTION"
                        binding.tvQuestion.text = state.riddle.question
                        binding.tvLockedAppNameQ.text = "$appLabel is locked"
                        updateTimerDisplay(state.timerSeconds, isStage3 = false)
                        setHintText(state.riddle.hint)
                        scheduleHintReveal(45)
                        binding.cardWrongQ.visibility = View.GONE
                        binding.etAnswer.text?.clear()
                    }

                    is SessionState.Stage2 -> {
                        // Animate transition: slide left
                        val slideIn = AnimationUtils.loadAnimation(this@ThreeStageLockActivity,
                            android.R.anim.slide_in_left)
                        binding.panelQuestion.startAnimation(slideIn)
                        showQuestionPanel()
                        setStepIndicator(2)
                        binding.tvStageBadge.text = "CHALLENGE II — ABSTRACT REASONING"
                        binding.tvQuestion.text = state.riddle.question
                        binding.tvLockedAppNameQ.text = "$appLabel is locked"
                        updateTimerDisplay(state.timerSeconds, isStage3 = false)
                        setHintText(state.riddle.hint)
                        scheduleHintReveal(45)
                        binding.cardWrongQ.visibility = View.GONE
                        binding.etAnswer.text?.clear()
                        binding.etAnswer.requestFocus()
                    }

                    is SessionState.Stage3 -> {
                        hintJob?.cancel()
                        showStage3Panel()
                        populateStage3(state.challenge, appLabel)
                        updateTimerDisplay(state.timerSeconds, isStage3 = true)
                        binding.cardWrong3.visibility = View.GONE
                    }

                    is SessionState.WrongAnswer -> {
                        val msg = if (state.attemptsLeft > 0)
                            "✗  Incorrect.  ${state.attemptsLeft} attempt${if (state.attemptsLeft == 1) "" else "s"} remaining."
                        else
                            "✗  No attempts remaining. Initiating lockout…"

                        when (state.stage) {
                            1, 2 -> {
                                binding.tvWrongFeedback.text = msg
                                binding.cardWrongQ.visibility = View.VISIBLE
                                binding.cardWrongQ.startAnimation(
                                    AnimationUtils.loadAnimation(this@ThreeStageLockActivity,
                                        android.R.anim.fade_in))
                            }
                            3 -> {
                                binding.tvWrongFeedback3.text = msg
                                binding.cardWrong3.visibility = View.VISIBLE
                            }
                        }
                    }

                    is SessionState.LockedOut -> showLockedOut(state.unlocksAt, appLabel)

                    is SessionState.Solved -> showSolved()
                }
            }
        }
    }

    // ── Panel Switchers ───────────────────────────────────────────────────────

    private fun showLoading() {
        binding.loadingSpinner.visibility = View.VISIBLE
        binding.panelQuestion.visibility = View.GONE
        binding.panelStage3.visibility   = View.GONE
        binding.panelLockedOut.visibility = View.GONE
        binding.panelSolved.visibility   = View.GONE
    }

    private fun showQuestionPanel() {
        binding.loadingSpinner.visibility = View.GONE
        binding.panelQuestion.visibility  = View.VISIBLE
        binding.panelStage3.visibility    = View.GONE
        binding.panelLockedOut.visibility = View.GONE
        binding.panelSolved.visibility    = View.GONE
        binding.etAnswer.requestFocus()
    }

    private fun showStage3Panel() {
        binding.loadingSpinner.visibility = View.GONE
        binding.panelQuestion.visibility  = View.GONE
        binding.panelStage3.visibility    = View.VISIBLE
        binding.panelLockedOut.visibility = View.GONE
        binding.panelSolved.visibility    = View.GONE
        hideKeyboard()
        // Pulse animation on the master challenge card
        val pulse = AnimationUtils.loadAnimation(this, android.R.anim.fade_in)
        binding.panelStage3.startAnimation(pulse)
    }

    private fun showLockedOut(unlocksAt: Long, appLabel: String) {
        binding.loadingSpinner.visibility = View.GONE
        binding.panelQuestion.visibility  = View.GONE
        binding.panelStage3.visibility    = View.GONE
        binding.panelLockedOut.visibility = View.VISIBLE
        binding.panelSolved.visibility    = View.GONE
        hideKeyboard()

        val remaining = unlocksAt - System.currentTimeMillis()
        binding.tvLockoutMessage.text =
            "You failed the IQ challenge.\n$appLabel is locked for 5 minutes.\n\n" +
            "Reconsider your reasoning strategy before the next attempt."

        lockoutCountdownTimer?.cancel()
        lockoutCountdownTimer = object : CountDownTimer(remaining.coerceAtLeast(0), 1_000) {
            override fun onTick(ms: Long) {
                val m = TimeUnit.MILLISECONDS.toMinutes(ms)
                val s = TimeUnit.MILLISECONDS.toSeconds(ms) % 60
                binding.tvLockoutCountdown.text = "%d:%02d".format(m, s)
            }
            override fun onFinish() {
                binding.tvLockoutCountdown.text = "0:00"
                finish()
            }
        }.start()
    }

    private fun showSolved() {
        binding.loadingSpinner.visibility = View.GONE
        binding.panelQuestion.visibility  = View.GONE
        binding.panelStage3.visibility    = View.GONE
        binding.panelLockedOut.visibility = View.GONE
        binding.panelSolved.visibility    = View.VISIBLE
        hideKeyboard()

        binding.tvSolvedMessage.text =
            "You conquered all three intelligence challenges.\n\nAccess granted."

        // Reveal the relationship explanation with a short delay for dramatic effect
        lifecycleScope.launch {
            delay(600)
            val explanation = viewModel.lastExplanation.ifBlank {
                "You correctly identified the hidden mathematical relationship between your two answers."
            }
            binding.tvExplanation.text = explanation
            binding.cardExplanation.visibility = View.VISIBLE
            binding.cardExplanation.startAnimation(
                AnimationUtils.loadAnimation(this@ThreeStageLockActivity, android.R.anim.fade_in))
        }
    }

    // ── Stage 3 Population ────────────────────────────────────────────────────

    private fun populateStage3(challenge: MasterChallenge, appLabel: String) {
        binding.tvLockedAppName3.text = "$appLabel is locked"
        binding.tvRecapAnswer1.text = viewModel.lastAnswer1
        binding.tvRecapAnswer2.text = viewModel.lastAnswer2

        binding.tvMasterQuestion.text = challenge.question

        // Build 6 option buttons dynamically
        binding.llOptions.removeAllViews()
        challenge.options.forEachIndexed { idx, optionText ->
            val btn = MaterialButton(
                this,
                null,
                com.google.android.material.R.attr.materialButtonOutlinedStyle
            ).apply {
                text = "${('A' + idx)}.  $optionText"
                textSize = 13f
                setPadding(16, 14, 16, 14)
                isAllCaps = false
                setTextColor(resources.getColor(android.R.color.white, theme))
                strokeColor = resources.getColorStateList(R.color.purple_200, theme)
                layoutParams = android.widget.LinearLayout.LayoutParams(
                    android.widget.LinearLayout.LayoutParams.MATCH_PARENT,
                    android.widget.LinearLayout.LayoutParams.WRAP_CONTENT
                ).apply { setMargins(0, 0, 0, 10) }
                tag = idx
                setOnClickListener { onOptionSelected(idx) }
            }
            binding.llOptions.addView(btn)
        }
    }

    private fun onOptionSelected(selectedIndex: Int) {
        // Visually mark selected button
        for (i in 0 until binding.llOptions.childCount) {
            val btn = binding.llOptions.getChildAt(i) as? MaterialButton
            btn?.strokeWidth = if (i == selectedIndex) 3 else 1
        }
        viewModel.submitStage3Choice(selectedIndex)
    }

    // ── Timer Display ─────────────────────────────────────────────────────────

    private fun updateTimerDisplay(seconds: Int, isStage3: Boolean) {
        val max = ThreeStageViewModel.STAGE_TIMER_SECONDS
        val progress = (seconds.toFloat() / max * 100).toInt()

        if (isStage3) {
            binding.tvTimer3.text = seconds.toString()
            binding.timerProgress3.setProgressCompat(progress, true)
            binding.timerProgress3.max = 100
            // Turn red when < 20s
            val color = if (seconds <= 20)
                resources.getColor(android.R.color.holo_red_light, theme)
            else
                resources.getColor(R.color.gold, theme)
            binding.tvTimer3.setTextColor(color)
        } else {
            binding.tvTimer.text = seconds.toString()
            binding.timerProgress.setProgressCompat(progress, true)
            binding.timerProgress.max = 100
            val color = if (seconds <= 20)
                resources.getColor(android.R.color.holo_red_light, theme)
            else
                resources.getColor(R.color.purple_200, theme)
            binding.tvTimer.setTextColor(color)
        }
    }

    // ── Step Indicator ────────────────────────────────────────────────────────

    private fun setStepIndicator(activeStage: Int) {
        val active   = R.drawable.bg_step_active
        val done     = R.drawable.bg_step_done
        val inactive = R.drawable.bg_step_inactive

        binding.stepDot1.setBackgroundResource(when {
            activeStage > 1 -> done
            activeStage == 1 -> active
            else -> inactive
        })
        binding.stepDot2.setBackgroundResource(when {
            activeStage > 2 -> done
            activeStage == 2 -> active
            else -> inactive
        })
        binding.stepDot3.setBackgroundResource(inactive)
    }

    // ── Hint ──────────────────────────────────────────────────────────────────

    private fun setHintText(hint: String) {
        binding.tvHint.text = hint
        binding.cardHint.visibility = View.GONE
    }

    private fun scheduleHintReveal(afterSeconds: Int) {
        hintJob?.cancel()
        hintJob = lifecycleScope.launch {
            delay(afterSeconds * 1_000L)
            if (binding.panelQuestion.visibility == View.VISIBLE) {
                binding.cardHint.visibility = View.VISIBLE
                binding.cardHint.startAnimation(
                    AnimationUtils.loadAnimation(this@ThreeStageLockActivity,
                        android.R.anim.fade_in))
            }
        }
    }

    // ── Button Setup ──────────────────────────────────────────────────────────

    private fun setupButtons() {
        // Stage 1 & 2: submit typed answer
        binding.btnSubmitAnswer.setOnClickListener {
            val input = binding.etAnswer.text?.toString().orEmpty().trim()
            if (input.isNotEmpty()) {
                hideKeyboard()
                viewModel.submitAnswer(input)
            }
        }

        // Keyboard "Done" action also submits
        binding.etAnswer.setOnEditorActionListener { _, actionId, _ ->
            if (actionId == EditorInfo.IME_ACTION_DONE) {
                binding.btnSubmitAnswer.performClick()
                true
            } else false
        }

        // Close buttons → cancel session and dismiss
        binding.btnCloseQ.setOnClickListener { confirmClose() }
        binding.btnClose3.setOnClickListener { confirmClose() }

        // Solved: open the app
        binding.btnOpenApp.setOnClickListener { finish() }
    }

    private fun confirmClose() {
        viewModel.cancelSession()
        finish()
    }

    // ── Dismiss Receiver ──────────────────────────────────────────────────────

    private val dismissReceiver = object : BroadcastReceiver() {
        override fun onReceive(context: Context, intent: Intent) {
            if (intent.action == ACTION_DISMISS) finish()
        }
    }

    private fun setupDismissReceiver() {
        val filter = IntentFilter(ACTION_DISMISS)
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            registerReceiver(dismissReceiver, filter, RECEIVER_NOT_EXPORTED)
        } else {
            registerReceiver(dismissReceiver, filter)
        }
    }

    // ── Keyboard ──────────────────────────────────────────────────────────────

    private fun hideKeyboard() {
        val imm = getSystemService(Context.INPUT_METHOD_SERVICE) as InputMethodManager
        currentFocus?.let { imm.hideSoftInputFromWindow(it.windowToken, 0) }
    }
}
